server:
  port: 9060
  servlet:
    context-path: /video
spring:
  application:
    name: video-service
  cloud:
    nacos:
      discovery:
#        server-addr: 8.129.20.24:8848 #nacos aliyun
        server-addr: 127.0.0.1:8848 #nacos local http://192.168.103.1:8848/nacos/index.html
        username: nacos
        password: nacos

